# Generated by Django 3.0.5 on 2020-07-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('folder_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud.Folder')),
            ],
        ),
    ]
