# Generated by Django 3.0.5 on 2020-07-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_auto_20200711_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='shortened_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
