# Generated by Django 3.0.5 on 2020-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_files_shortened_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
