# Generated by Django 3.0.5 on 2020-07-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedin',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
