# Generated by Django 3.0.5 on 2020-07-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_auto_20200720_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
